### ISSUE TITLE
Question: How generate documentation about variables  $scope

### ISSUE THREAD

**Issue by kevincaradant** [nikhilmodak/gulp-ngdocs#101]
Hi,

I discovered this library which is very great but i don't understand, how can i generate doc just on $scope variables. Is it any way to do this ?

I tried something like this but it does not work
```
* @element $scope
* @description
* My description AZERTYUI
$scope.template="templateDaily";
```

Thank you and sorry if it's not the good repo to ask this :/

Edit: The best i found is:

```
/**
* @ngdoc property
* @name app.object:templateSelectedDaily
* @description
* Theme by default for the daily tickets
*/
```
But i can't write => * @name app.object:$scope.templateSelectedDaily where $scope.templateSelectedDaily  is the name of the variable. So it's not perfect and maybe the wrong way to do this :)

**Comment by caseyhoward** [comment]
You should be documenting the public interface to your directives. I'm not sure why you would want to document things on the $scope. $scope and non-component controllers are pretty much deprecated. I usually just document examples of how to use the the directive. Things defined on the $scope (or component controller) are just implementation details.

You should be using components instead of controllers and templates. https://docs.angularjs.org/guide/component

**Comment by kevincaradant** [comment]
Hi, ok thank you. It was just to be very clear about my application because some $scope are a little bit complicated to understand in my project. But i'll follow your idea !
