### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by tommck** [nikhilmodak/gulp-ngdocs#119]
I really want to use this project, but I notice there are no commits since August and there are 12 outstanding pull requests.

Is this project dead?
If so, can someone take it over?

**Comment by andyperlitch** [comment]
For a brief time I had done some cursory maintenance on this project because @nikhilmodak had stopped actively working on it and I asked him to add me as an owner. I have since moved on though and have not kept up with maintenance as I do not personally use it in any of my current projects. I'll open a new issue with a call for new maintainers.
