### ISSUE TITLE
Don't know how to format @ngdoc: provider

### ISSUE THREAD

**Issue by bampakoa** [nikhilmodak/gulp-ngdocs#67]
Hi,

I tried to use **provider** directive with the plugin but I get the following error:

     Don't know how to format @ngdoc: provider

**Comment by bampakoa** [comment]
Anybody on this??

**Comment by JesseChrestler** [comment]
I just checked the documentation for [ngdocs](https://github.com/idanush/ngdocs/wiki/API-Docs-Syntax) and there is no **provider** ngdoc extension. However there is a service, which appears to be a catch all.
```
/**
* @ngdoc service
* @name MyCoolProvider
**/
```
I suppose you should suffix your provider name with the word Provider, and the same goes for Service and Factories as well.

**Comment by bampakoa** [comment]
@JesseChrestler I noticed that too in ndocs. But in the official AngularJS documentation they use **provider** as a keyword as you can see in [httpProvider documentation](https://github.com/angular/angular.js/blob/master/src/ng/http.js#L246)

**Comment by JesseChrestler** [comment]
@bampakoa so as it turns out gulp-ngdocs isn't using Dgeni (which is what the good folks of angularjs use) to generate it's documentation. So from that you can assume this doesn't use the dgeni-packages that are offered with dgeni; which has processors to support tags like @ngdoc provider and such. I've also noticed there is no support for @ngodoc event either.

Now that being said there aren't whole lot of options. Dgeni has limited documentation and a couple example projects. However they don't have great templates, yet. I am going to keep searching.

**Comment by bampakoa** [comment]
@JesseChrestler thnx for your feedback!

**Comment by LuizGsa21** [comment]
@JesseChrestler any luck on your search?

**Comment by JesseChrestler** [comment]
@LuizGsa21 I ended up abandoning gulp-ngdocs all together. The problem with using them is you can't rely on what documentation is being used by angularjs. Which is what you try to use as a reference. Angularjs Dgeni has limited documentation as well, which was quite frustrating. 
So what i did is went to angularjs source directly. I downloaded master (https://github.com/angular/angular.js/tree/master/docs) and tried to get it working using angularjs source. Well without too much trouble it worked. However there was a lot of dependencies back to github and things that I'd need to strip out (the build farms I use do not have internet access) to make it work for any project in a generic way. After a couple hours I was able to point it to my source and it was working with all the nice new features including @ngdoc: provider, and live running examples. It's really nice honestly. 

I could probably write a tutorial and include the base source so that you could also do the same for your projects. The site looks exactly the same as the one you find in the angularjs documentation with search and everything. (https://docs.angularjs.org/api)

**Comment by LuizGsa21** [comment]
@JesseChrestler wow that's awesome, thanks for replying back. :) I'm going to attempt to do what you did and hopefully it works out. If you do write a tutorial, let me know, it would be much appreciated.

**Comment by JesseChrestler** [comment]
@LuizGsa21 here is a seed that I setup. Nothing fancy but hopefully it will help you and anyone else looking for a similar solution.

https://github.com/JesseChrestler/angular-dgeni-seed

**Comment by Maus3rVonDutch** [comment]
Hi Jesse, awesome work! I'd like to give this a try also, I'm running into a problem however. Here is the stacktrace:
```
started configuring docs...
finished configuring docs...
[17:07:53] 'build:docs' errored after 562 ms
[17:07:53] TypeError: object is not a function
    at Function.v.extend.async (C:\Repositories\OtherTrunk\Source\NControl\NCore.Client\node_modules\dgeni\node_modules\validate.js\validate.js:196:14)
    at C:\Repositories\OtherTrunk\Source\NControl\NCore.Client\node_modules\dgeni\lib\Dgeni.js:166:23
    at _fulfilled (C:\Repositories\OtherTrunk\Source\NControl\NCore.Client\node_modules\dgeni\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Repositories\OtherTrunk\Source\NControl\NCore.Client\node_modules\dgeni\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Repositories\OtherTrunk\Source\NControl\NCore.Client\node_modules\dgeni\node_modules\q\q.js:796:13)
    at C:\Repositories\OtherTrunk\Source\NControl\NCore.Client\node_modules\dgeni\node_modules\q\q.js:857:14
    at runSingle (C:\Repositories\OtherTrunk\Source\NControl\NCore.Client\node_modules\dgeni\node_modules\q\q.js:137:13)
    at flush (C:\Repositories\OtherTrunk\Source\NControl\NCore.Client\node_modules\dgeni\node_modules\q\q.js:125:13)
    at process._tickCallback (node.js:419:13)
```

Any ideas what I'm doing wrong?

**Comment by JesseChrestler** [comment]
feel free to email me the steps you did. jessechrestler[at]gmail.com I would be more than happy to help you. I just grabbed a zip of the master. Extracted it into a folder. Went into that folder did an npm install. Then I ran the command gulp build:docs. Can send me an email and walk me through the steps you did?

**Comment by Maus3rVonDutch** [comment]
Hi, I was trying to run the gulp task by the task runner explorer from within Visual Studio. If I run the gulp task from the command prompt, it runs just fine. Thanks for the response, I'll try to debug it myself now I know where the problem lies.

**Comment by JesseChrestler** [comment]
Ok, great. If you run into any another issue post the issue on the seed project or send me an email.

**Comment by bampakoa** [comment]
@JesseChrestler nice work with your repo! I finally declared it as service and suffixed my provider with word **Provider**.
